### ISSUE TITLE
Quick Comments Shortcuts Modal

### ISSUE THREAD

**Issue by mezmi** [shu8/SE_OptionalFeatures#36]
The Quick Comments Shortcuts modal is currently displayed at the top of the screen, 100% width and offset to the right by 615.5px.   

When opening the modal from father down the page it is not visible, forcing the user to scroll up and over.

![offsetmodal](https://cloud.githubusercontent.com/assets/12533449/11326200/18472eb4-9118-11e5-9f35-2609f85e8c82.png)

This seems to be caused by this css style.

``` css
.SEAOP-centered {
    width:400px;
    z-index:1001;
    top:102px;
    left:615.5px;
    display:inline-block;
    margin-top:-95.5px;
    margin-left:-216px;
    overflow:auto;
    height:90%;   
}
```

And this is the line where the modal width is set to 100%
`$('#quickCommentShortcuts').css('width', '100%').css('position', 'absolute').draggable();`

~~It also appears that after the modal has been opened and closed it will not reopen.~~

Perhaps another css rule should be added to handle this specific modal.

I changed the width to 75%, left to 12.5% and _tried_ adjusting the top but haven't quite got it yet.

``` css
#quickCommentsShortcuts .SEAOP-centered {
    width: 75%;
    height:90%;   
    z-index:1001;
    top:5%;
    left:12.5%;
    display:inline-block;
    overflow:auto;
}
```
